### PR TITLE
Implemented missing workflows

### PR DESCRIPTION
**Pull request by SergioCasCeb**
* Implemented the missing workflows (SDK and Platform) 
* Added the respective animations
* Made them responsive

### CODE REVIEW

**Comment by egekorkan** [comment]
I like them enough to merge for now. Current page has nothing :) 

The platform can be improved by highlighting a high number of devices aspect. That is why we want to have a TDD.

**Comment by egekorkan** [comment]
@danielpeintner @relu91 please provide an opion if this can be merged and reiterated or whether we should change something quickly

**Comment by SergioCasCeb** [comment]
Okay, @egekorkan and @danielpeintner the responsiveness bug should be fixed now.

**Comment by danielpeintner** [comment]
Question: On https://www.thingweb.io I noticed that the 3rd workflow does now miss the image. Is this done on purpose? I think I remember seeing an image animation there as well!?

**Comment by danielpeintner** [comment]
Mhh, not sure ... personally I do not think it is a "local" cache issue on my side since I don't see the image neither on my windows box nor on my mobile phone. Do you see the 3rd image on your side?

**Comment by danielpeintner** [comment]
FYI: the workflow illustration seems to be empty `div`, see 

image

**Comment by SergioCasCeb** [comment]
> FYI: the workflow illustration seems to be empty `div`, see 
> 
> image
> 

As I mentioned, it is not showing the latest updates for some reason. Because that was fixed an added in this PR.

**Comment by egekorkan** [comment]
Due to https://github.com/eclipse-thingweb/website/issues/92 it is not automatically deployed. I need to deploy it manually. Sorry about that

**Comment by egekorkan** [comment]
@SergioCasCeb @danielpeintner should be done now. I will open an issue for eclipse too

**Comment by SergioCasCeb** [comment]
> @SergioCasCeb @danielpeintner should be done now. I will open an issue for eclipse too

I can see the updated changes now. Thank you @egekorkan

**Pull request merged**
