### PR TITLE
Reposition the adopters scroller

### PR DESCRIPTION
**Pull request by SergioCasCeb**
To provide a preview of where the adopters' scroller might fit best, I have temporarily added it in three different sections:

- Header
- About/Value Proposition section
- Original placement (for comparison)

Personally, I lean towards placing it in the header, as it quickly builds trust with users. However, the original location also works well contextually. 

Once a final placement is decided, I will clean up the code and remove the unwanted ones.

### CODE REVIEW

**Comment by danielpeintner** [comment]
I like the "header" version also.
Anyhow, given that the numbers (Discord, GitHub and Adopters) is mention in the end I still think it is best there...

**Comment by egekorkan** [comment]
I like the header more than the about. Not sure about the original vs header. @relu91 @JKRhb any opinion?

**Comment by relu91** [comment]
+1 for the header version, I agree with the feedback that we collected. Works good on mobile too.

**Comment by JKRhb** [comment]
I also like the header version better than the about version :) I was wondering, though, whether there should be a small tagline indicating that the logos belong to adopters, to give a bit more context.

**Comment by SergioCasCeb** [comment]
So far, the header version might have the edge a bit. How should we proceed from here?

**Pull request merged**
